### ISSUE TITLE
Explicit dependency of React 16.7.0 causes problems with Jest

### ISSUE THREAD

**Issue by lzhuor** [blockchain/components#252]
In `blockchain-wallet-v4-frontend`, `@blockchain-com/components` causes Jest fails to shallow render components with Hooks (introduced since React v16.8.0) because explicit React version dependency of `v16.7.0` causes `blockchain-wallet-v4-frontend/packages/blockchain-info-components` to use `v16.7.0` instead of `v16.8.6`.

**Error in Jest test (`shallow` render):**
![image](https://user-images.githubusercontent.com/14172220/62970118-559cc580-be41-11e9-9d28-288f31e76de8.png)
```
    Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
    1. You might have mismatching versions of React and the renderer (such as React DOM)
    2. You might be breaking the Rules of Hooks
    3. You might have more than one copy of React in the same app
    See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

**Error in `npm ls react`:**
![image](https://user-images.githubusercontent.com/14172220/62970198-841aa080-be41-11e9-8314-9df5f5c0240c.png)

**Solution (a or b)**
a. Change `react: "16.7.0"` to `react: "^16.7.0"`
b. Upgrade `react: "16.7.0"` to `react: "16.8.6`

**Comment by Lyncee59** [comment]
Hey @lzhuor , taking a look at that now.

Got kinda busy recently !

**Comment by schnogz** [comment]
This is actually an issue with @storybook. Closing
